import { PostType } from '../types/types';

export const PostArr = [
	{
		category: 'Marketing',
		img: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/IMG-last.png?alt=media&token=00086881-6f54-4e88-bfec-4585e3f71c8b&_gl=1*hnszy4*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTUxMTU2Ni4xMC4xLjE2ODU1MTE2MzEuMC4wLjA.',
		month: 'February',
		day: 28,
		title: 'How to Maximize Your ROI Through Scientific SEM?',
		desc: 'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. ',
		name: 'Jane Cooper',
		time: '8 min read',
		pfp: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/avatar-7.png?alt=media&token=80f94d81-7921-4113-9181-85aa1e1228c7&_gl=1*1b0yrms*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTUxMTU2Ni4xMC4xLjE2ODU1MTE2NTkuMC4wLjA.',
		tags: ['Marketing', 'Management', 'Community', 'Business'],
	},
	{
		category: 'Marketing',
		img: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/arabman.png?alt=media&token=6e04354e-64c2-4bce-b807-7b79aca4cae3&_gl=1*m3dxqc*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQzOTA1Ni4wLjAuMA..',
		month: 'Jul',
		day: 12,
		title: 'The 7 Best Things About Event',
		desc: 'Moment in the life of any aspiring astronomer of that it is time to.',
		name: 'Arlene McCoy',
		time: '8 min read',
		pfp: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/avatar-1.png?alt=media&token=b8654c4e-385a-4c9c-bb30-1475fd20f65f&_gl=1*4y1zis*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQ0MDQ2NS4wLjAuMA..',
		tags: ['Marketing', 'Management', 'Community', 'Business'],
	},
	{
		category: 'Community',
		img: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/IMG-3.png?alt=media&token=6aaae566-d924-4f46-9868-6db9cd0df29f&_gl=1*qi34nh*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQzOTM3MS4wLjAuMA..',
		month: 'Sep',
		day: 24,
		title: 'Event Is Your Worst Enemy. 7 Ways To Defeat It',
		desc: 'Moment in the life of any aspiring astronomer of that it is time to.',
		name: 'Cody Fisher',
		time: '8 min read',
		pfp: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/avatar-2.png?alt=media&token=ad9f9fb3-2b94-4f1a-ae4d-49a2c48c1bd6&_gl=1*1x41ved*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQ0MDQ3OC4wLjAuMA..',
		tags: ['Community', 'Design', 'Management', 'HR & Recruiting'],
	},
	{
		category: 'Tutorials',
		img: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/IMG.png?alt=media&token=b2e0e577-ecef-4102-8ce4-f5a7c6cd9210&_gl=1*v8bijy*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQzOTA5OC4wLjAuMA..',
		month: 'Jul',
		day: 18,
		title: 'The 7 Biggest Event Mistakes You Can Easily...',
		desc: 'Moment in the life of any aspiring astronomer of that it is time to.',
		name: 'Pamela Mclellan',
		time: '12 min read',
		pfp: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/avatar-3.png?alt=media&token=ba5b5b05-493a-4597-95be-9311e66d741d&_gl=1*vk2o05*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQ0MDUwMi4wLjAuMA..',
		tags: ['Development', 'Tutorials', 'Marketing', 'Management'],
	},
	{
		category: 'Business',
		img: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/IMG-4.png?alt=media&token=d362397f-d063-4257-b060-324cc63e1429&_gl=1*1a9bi4a*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQzOTI5OS4wLjAuMA..',
		month: 'Jul',
		day: 18,
		title: 'Master The Art Of Event With These 7 Tips',
		desc: 'Moment in the life of any aspiring astronomer of that it is time to.',
		name: 'Cruz Truong',
		time: '12 min read',
		pfp: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/avatar-4.png?alt=media&token=04cbd91e-6b84-4b79-a551-ce11def28e00&_gl=1*mt1cwe*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQ0MDUyNy4wLjAuMA..',
		tags: ['Business', 'Management', 'Marketing', 'Community'],
	},
	{
		category: 'Management',
		img: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/IMG-1.png?alt=media&token=fac7c118-43ba-4f3b-88c5-f51f2f35c15f&_gl=1*89nhkn*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQzOTEyNi4wLjAuMA..',
		month: 'Jul',
		day: 18,
		title: 'The 7 Best Things About Event',
		desc: 'Moment in the life of any aspiring astronomer of that it is time to.',
		name: 'Donell Wicks',
		time: '10 min read',
		pfp: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/avatar-5.png?alt=media&token=9e95323c-f62d-4084-9fe9-cc6332dd9be4&_gl=1*2gyd5s*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQ0MDU1MC4wLjAuMA..',
		tags: ['Community', 'Management', 'Marketing', 'HR & Recruiting'],
	},
	{
		category: 'Community',
		img: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/IMG-5.png?alt=media&token=51e21c81-5a81-4097-bba6-83da00d5c986&_gl=1*1umyzx7*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQzOTQyMS4wLjAuMA..',
		month: 'Jul',
		day: 18,
		title: "Thinking About Event? 7 Reasons Why It's Time...",
		desc: 'Moment in the life of any aspiring astronomer of that it is time to.',
		name: 'Margaret Donnelly',
		time: '10 min read',
		pfp: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/avatar-6.png?alt=media&token=bce8202d-110a-49cc-bb24-42a097b76be2&_gl=1*87tum6*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQ0MDU3NS4wLjAuMA..',
		tags: ['Community', 'Business', 'Marketing', 'HR & Recruiting'],
	},
	{
		category: 'Tutorials',
		img: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/IMG-2.png?alt=media&token=ddfd6e42-d2d7-42c1-bf05-c53758f92deb&_gl=1*17ymoma*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQzOTE1NC4wLjAuMA..',
		month: 'Jul',
		day: 18,
		title: "Don't Waste Time! 7 Facts Until You Reach Your...",
		desc: 'Moment in the life of any aspiring astronomer of that it is time to.',
		name: 'Raihan Nieves',
		time: '10 min read',
		pfp: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/avatar-7.png?alt=media&token=80f94d81-7921-4113-9181-85aa1e1228c7&_gl=1*nsfdfm*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQ0MDU4OC4wLjAuMA..',
		tags: ['Marketing', 'Management', 'Tutorials', 'Design'],
	},
	{
		category: 'Management',
		img: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/IMG-6.png?alt=media&token=5811680e-352c-437e-ab8e-39d4c4c6a78b&_gl=1*ffwhl4*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQzOTYxMy4wLjAuMA..',
		month: 'Dec',
		day: 29,
		title: "Thinking About Event? 7 Reasons Why It's ...",
		desc: 'Moment in the life of any aspiring astronomer of that it is time to.',
		name: 'Marvin McKinney',
		time: '8 min read',
		pfp: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/avatar-8.png?alt=media&token=168cf134-a4c9-48f0-b135-17f589cbc5d0&_gl=1*1rg2spx*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQ0MDYwNC4wLjAuMA..',
		tags: ['Marketing', 'Management', 'Business', 'Community'],
	},
	//!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	// Marketing Category
	{
		category: 'Marketing',
		img: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/arabman.png?alt=media&token=6e04354e-64c2-4bce-b807-7b79aca4cae3&_gl=1*m3dxqc*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQzOTA1Ni4wLjAuMA..',
		month: 'Jul',
		day: 12,
		title: 'The 7 Best Things About Marketing',
		desc: 'Discover the key aspects that make marketing an essential tool for businesses.',
		name: 'Arlene McCoy',
		time: '8 min read',
		pfp: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/avatar-1.png?alt=media&token=b8654c4e-385a-4c9c-bb30-1475fd20f65f&_gl=1*4y1zis*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQ0MDQ2NS4wLjAuMA..',
		tags: ['Marketing', 'Development', 'Business', 'Community'],
	},
	{
		category: 'Marketing',
		month: 'Sep',
		img: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/IMG-3.png?alt=media&token=6aaae566-d924-4f46-9868-6db9cd0df29f&_gl=1*qi34nh*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQzOTM3MS4wLjAuMA..',
		day: 24,
		title: 'The Future of Marketing: Trends and Strategies',
		desc: 'Explore the latest trends and strategies shaping the future of marketing.',
		name: 'Cody Fisher',
		time: '8 min read',
		pfp: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/avatar-2.png?alt=media&token=ad9f9fb3-2b94-4f1a-ae4d-49a2c48c1bd6&_gl=1*1x41ved*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQ0MDQ3OC4wLjAuMA..',
		tags: ['Marketing', 'Management', 'Design', 'Community'],
	},
	{
		category: 'Marketing',
		img: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/IMG-4.png?alt=media&token=d362397f-d063-4257-b060-324cc63e1429&_gl=1*1a9bi4a*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQzOTI5OS4wLjAuMA..',
		month: 'Jul',
		day: 18,
		title: 'Effective Marketing Campaigns: Lessons Learned',
		desc: 'Learn valuable lessons from successful marketing campaigns and apply them to your own business.',
		name: 'Pamela Mclellan',
		time: '12 min read',
		pfp: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/avatar-4.png?alt=media&token=04cbd91e-6b84-4b79-a551-ce11def28e00&_gl=1*mt1cwe*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQ0MDUyNy4wLjAuMA..',
		tags: ['Marketing', 'Management', 'Development', 'Business'],
	},
	{
		category: 'Marketing',
		month: 'Jul',
		img: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/IMG-1.png?alt=media&token=fac7c118-43ba-4f3b-88c5-f51f2f35c15f&_gl=1*89nhkn*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQzOTEyNi4wLjAuMA..',
		day: 18,
		title: 'Maximizing ROI: Strategies for Marketing Success',
		desc: 'Discover effective strategies to maximize return on investment (ROI) in your marketing efforts.',
		name: 'Cruz Truong',
		time: '12 min read',
		pfp: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/avatar-5.png?alt=media&token=9e95323c-f62d-4084-9fe9-cc6332dd9be4&_gl=1*2gyd5s*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQ0MDU1MC4wLjAuMA..',
		tags: ['Marketing', 'Business', 'Community', 'HR & Recruiting'],
	},

	// Community Category
	{
		category: 'Community',
		img: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/arabman.png?alt=media&token=6e04354e-64c2-4bce-b807-7b79aca4cae3&_gl=1*m3dxqc*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQzOTA1Ni4wLjAuMA..',
		month: 'Jul',
		day: 18,
		title: 'Building a Strong Community: Tips and Best Practices',
		desc: 'Learn how to create and nurture a strong community around your brand or organization.',
		name: 'Donell Wicks',
		time: '10 min read',
		pfp: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/avatar-1.png?alt=media&token=b8654c4e-385a-4c9c-bb30-1475fd20f65f&_gl=1*4y1zis*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQ0MDQ2NS4wLjAuMA..',
		tags: ['Community', 'Marketing', 'Management', 'Business'],
	},
	{
		category: 'Community',
		img: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/IMG-3.png?alt=media&token=6aaae566-d924-4f46-9868-6db9cd0df29f&_gl=1*qi34nh*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQzOTM3MS4wLjAuMA..',
		month: 'Jul',
		day: 18,
		title: 'Engaging Your Community: Strategies for Success',
		desc: 'Discover effective strategies to engage and connect with your community members.',
		name: 'Margaret Donnelly',
		time: '10 min read',
		pfp: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/avatar-2.png?alt=media&token=ad9f9fb3-2b94-4f1a-ae4d-49a2c48c1bd6&_gl=1*1x41ved*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQ0MDQ3OC4wLjAuMA..',
		tags: ['Community', 'Marketing', 'HR & Recruiting', 'Design'],
	},
	{
		category: 'Community',
		img: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/IMG-4.png?alt=media&token=d362397f-d063-4257-b060-324cc63e1429&_gl=1*1a9bi4a*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQzOTI5OS4wLjAuMA..',
		month: 'Jul',
		day: 18,
		title: 'Creating Positive Impact: Community Outreach Programs',
		desc: 'Explore community outreach programs and their impact on businesses and society.',
		name: 'Raihan Nieves',
		time: '10 min read',
		pfp: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/avatar-4.png?alt=media&token=04cbd91e-6b84-4b79-a551-ce11def28e00&_gl=1*mt1cwe*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQ0MDUyNy4wLjAuMA..',
		tags: ['Community', 'Business', 'Marketing', 'Management'],
	},
	{
		category: 'Community',
		img: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/IMG-1.png?alt=media&token=fac7c118-43ba-4f3b-88c5-f51f2f35c15f&_gl=1*89nhkn*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQzOTEyNi4wLjAuMA..',
		month: 'Jul',
		day: 18,
		title: 'Fostering Collaboration: Building Strong Community Partnerships',
		desc: 'Learn how to foster collaboration and build strong partnerships within your community.',
		name: 'Marvin McKinney',
		time: '8 min read',
		pfp: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/avatar-5.png?alt=media&token=9e95323c-f62d-4084-9fe9-cc6332dd9be4&_gl=1*2gyd5s*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQ0MDU1MC4wLjAuMA..',
		tags: ['Community', 'Business', 'Marketing', 'HR & Recruiting'],
	},

	// Tutorials Category
	{
		category: 'Tutorials',
		img: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/arabman.png?alt=media&token=6e04354e-64c2-4bce-b807-7b79aca4cae3&_gl=1*m3dxqc*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQzOTA1Ni4wLjAuMA..',
		month: 'Jul',
		day: 12,
		title: 'Mastering Web Development: A Comprehensive Tutorial',
		desc: 'Embark on a comprehensive tutorial to master the art of web development.',
		name: 'Arlene McCoy',
		time: '8 min read',
		pfp: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/avatar-1.png?alt=media&token=b8654c4e-385a-4c9c-bb30-1475fd20f65f&_gl=1*4y1zis*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQ0MDQ2NS4wLjAuMA..',
		tags: ['Tutorials', 'Development', 'Design', 'Community'],
	},
	{
		category: 'Tutorials',
		img: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/IMG-3.png?alt=media&token=6aaae566-d924-4f46-9868-6db9cd0df29f&_gl=1*qi34nh*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQzOTM3MS4wLjAuMA..',
		month: 'Sep',
		day: 24,
		title: 'Learn Graphic Design from Scratch: Step-by-Step Tutorial',
		desc: 'Start your journey in graphic design with this step-by-step tutorial for beginners.',
		name: 'Cody Fisher',
		time: '8 min read',
		pfp: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/avatar-2.png?alt=media&token=ad9f9fb3-2b94-4f1a-ae4d-49a2c48c1bd6&_gl=1*1x41ved*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQ0MDQ3OC4wLjAuMA..',
		tags: ['Tutorials', 'Design', 'Development', 'Community'],
	},
	{
		category: 'Tutorials',
		img: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/IMG-5.png?alt=media&token=51e21c81-5a81-4097-bba6-83da00d5c986&_gl=1*1umyzx7*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQzOTQyMS4wLjAuMA..',
		month: 'Jul',
		day: 18,
		title: 'Mastering Data Analysis: Practical Tutorial for Analysts',
		desc: 'Gain practical skills and techniques to master data analysis as an analyst.',
		name: 'Pamela Mclellan',
		time: '12 min read',
		pfp: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/avatar-6.png?alt=media&token=bce8202d-110a-49cc-bb24-42a097b76be2&_gl=1*87tum6*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQ0MDU3NS4wLjAuMA..',
		tags: ['Tutorials', 'Development', 'Marketing', 'Management'],
	},
	{
		category: 'Tutorials',
		img: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/IMG-6.png?alt=media&token=5811680e-352c-437e-ab8e-39d4c4c6a78b&_gl=1*ffwhl4*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQzOTYxMy4wLjAuMA..',
		month: 'Jul',
		day: 18,
		title: 'Photography Basics: A Beginner-Friendly Tutorial',
		desc: 'Learn the basics of photography and start capturing stunning images.',
		name: 'Cruz Truong',
		time: '12 min read',
		pfp: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/avatar-8.png?alt=media&token=168cf134-a4c9-48f0-b135-17f589cbc5d0&_gl=1*1rg2spx*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQ0MDYwNC4wLjAuMA..',
		tags: ['Tutorials', 'Design', 'Community', 'Marketing'],
	},

	// Business Category
	{
		category: 'Business',
		img: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/arabman.png?alt=media&token=6e04354e-64c2-4bce-b807-7b79aca4cae3&_gl=1*m3dxqc*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQzOTA1Ni4wLjAuMA..',
		month: 'Jul',
		day: 18,
		title: 'Startup Success: Key Strategies for New Businesses',
		desc: 'Explore essential strategies to achieve startup success and overcome challenges.',
		name: 'Donell Wicks',
		time: '10 min read',
		pfp: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/avatar-1.png?alt=media&token=b8654c4e-385a-4c9c-bb30-1475fd20f65f&_gl=1*4y1zis*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQ0MDQ2NS4wLjAuMA..',
		tags: ['Business', 'Marketing', 'Management', 'Community'],
	},
	{
		category: 'Business',
		img: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/IMG-3.png?alt=media&token=6aaae566-d924-4f46-9868-6db9cd0df29f&_gl=1*qi34nh*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQzOTM3MS4wLjAuMA..',
		month: 'Jul',
		day: 18,
		title: 'Financial Planning for Small Businesses: Expert Advice',
		desc: 'Get expert advice on financial planning and management for small businesses.',
		name: 'Margaret Donnelly',
		time: '10 min read',
		pfp: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/avatar-2.png?alt=media&token=ad9f9fb3-2b94-4f1a-ae4d-49a2c48c1bd6&_gl=1*1x41ved*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQ0MDQ3OC4wLjAuMA..',
		tags: ['Business', 'Marketing', 'Banking', 'Management'],
	},
	{
		category: 'Business',
		img: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/IMG-5.png?alt=media&token=51e21c81-5a81-4097-bba6-83da00d5c986&_gl=1*1umyzx7*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQzOTQyMS4wLjAuMA..',
		month: 'Jul',
		day: 18,
		title: 'Scaling Your Business: Strategies for Growth',
		desc: 'Discover effective strategies for scaling and growing your business.',
		name: 'Raihan Nieves',
		time: '10 min read',
		pfp: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/avatar-6.png?alt=media&token=bce8202d-110a-49cc-bb24-42a097b76be2&_gl=1*87tum6*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQ0MDU3NS4wLjAuMA..',
		tags: ['Business', 'Marketing', 'Management', 'HR & Recruiting'],
	},
	{
		category: 'Business',
		img: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/IMG-6.png?alt=media&token=5811680e-352c-437e-ab8e-39d4c4c6a78b&_gl=1*ffwhl4*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQzOTYxMy4wLjAuMA..',
		month: 'Dec',
		day: 29,
		title: 'Building a Successful E-commerce Business: Tips and Insights',
		desc: 'Learn valuable tips and insights to build a successful e-commerce business.',
		name: 'Marvin McKinney',
		time: '8 min read',
		pfp: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/avatar-8.png?alt=media&token=168cf134-a4c9-48f0-b135-17f589cbc5d0&_gl=1*1rg2spx*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQ0MDYwNC4wLjAuMA..',
		tags: ['Business', 'Marketing', 'Development', 'Community'],
	},

	// Management Category
	{
		category: 'Management',
		img: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/arabman.png?alt=media&token=6e04354e-64c2-4bce-b807-7b79aca4cae3&_gl=1*m3dxqc*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQzOTA1Ni4wLjAuMA..',
		month: 'Jul',
		day: 12,
		title: 'Effective Team Management: Strategies for Success',
		desc: 'Discover effective strategies to manage and lead your team towards success.',
		name: 'Arlene McCoy',
		time: '8 min read',
		pfp: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/avatar-1.png?alt=media&token=b8654c4e-385a-4c9c-bb30-1475fd20f65f&_gl=1*4y1zis*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQ0MDQ2NS4wLjAuMA..',
		tags: ['Management', 'Business', 'Community', 'Marketing'],
	},
	{
		category: 'Management',
		img: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/IMG-3.png?alt=media&token=6aaae566-d924-4f46-9868-6db9cd0df29f&_gl=1*qi34nh*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQzOTM3MS4wLjAuMA..',
		month: 'Sep',
		day: 24,
		title: 'Leadership in the Digital Age: Key Skills and Insights',
		desc: 'Learn key skills and insights to become an effective leader in the digital age.',
		name: 'Cody Fisher',
		time: '8 min read',
		pfp: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/avatar-2.png?alt=media&token=ad9f9fb3-2b94-4f1a-ae4d-49a2c48c1bd6&_gl=1*1x41ved*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQ0MDQ3OC4wLjAuMA..',
		tags: ['Management', 'Marketing', 'Development', 'HR & Recruiting'],
	},
	{
		category: 'Management',
		img: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/IMG-5.png?alt=media&token=51e21c81-5a81-4097-bba6-83da00d5c986&_gl=1*1umyzx7*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQzOTQyMS4wLjAuMA..',
		month: 'Jul',
		day: 18,
		title: 'Conflict Resolution in the Workplace: Best Practices',
		desc: 'Discover best practices for resolving conflicts and maintaining a harmonious workplace.',
		name: 'Pamela Mclellan',
		time: '12 min read',
		pfp: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/avatar-6.png?alt=media&token=bce8202d-110a-49cc-bb24-42a097b76be2&_gl=1*87tum6*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQ0MDU3NS4wLjAuMA..',
		tags: ['Management', 'Business', 'Community', 'HR & Recruiting'],
	},
	{
		category: 'Management',
		img: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/IMG-6.png?alt=media&token=5811680e-352c-437e-ab8e-39d4c4c6a78b&_gl=1*ffwhl4*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQzOTYxMy4wLjAuMA..',
		month: 'Jul',
		day: 18,
		title: 'Strategic Decision Making: A Guide for Managers',
		desc: 'Master the art of strategic decision making and enhance your managerial skills.',
		name: 'Cruz Truong',
		time: '12 min read',
		pfp: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/avatar-8.png?alt=media&token=168cf134-a4c9-48f0-b135-17f589cbc5d0&_gl=1*1rg2spx*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQ0MDYwNC4wLjAuMA..',
		tags: ['Management', 'Business', 'Marketing', 'Development'],
	},
] as Array<PostType>;

export const PostArr_ru = [
	{
		category: 'Маркетинг',
		img: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/IMG-last.png?alt=media&token=00086881-6f54-4e88-bfec-4585e3f71c8b&_gl=1*hnszy4*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTUxMTU2Ni4xMC4xLjE2ODU1MTE2MzEuMC4wLjA.',
		month: 'Февраль',
		day: 28,
		title: 'Как максимизировать ваш ROI через научный SEM?',
		desc: 'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint.',
		name: 'Джейн Купер',
		time: '8 мин чтения',
		pfp: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/avatar-7.png?alt=media&token=80f94d81-7921-4113-9181-85aa1e1228c7&_gl=1*1b0yrms*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTUxMTU2Ni4xMC4xLjE2ODU1MTE2NTkuMC4wLjA.',
		tags: ['Маркетинг', 'Управление', 'Сообщество', 'Бизнес'],
	},
	{
		category: 'Сообщество',
		img: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/arabman.png?alt=media&token=6e04354e-64c2-4bce-b807-7b79aca4cae3&_gl=1*m3dxqc*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQzOTA1Ni4wLjAuMA..',
		month: 'Июль',
		day: 12,
		title: '7 лучших вещей о событии',
		desc: 'Moment in the life of any aspiring astronomer of that it is time to.',
		name: 'Арлин Маккой',
		time: '8 мин чтения',
		pfp: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/avatar-1.png?alt=media&token=b8654c4e-385a-4c9c-bb30-1475fd20f65f&_gl=1*4y1zis*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQ0MDQ2NS4wLjAuMA..',
		tags: ['Маркетинг', 'Управление', 'Сообщество', 'Бизнес'],
	},
	{
		category: 'Обучение',
		img: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/IMG-4.png?alt=media&token=d362397f-d063-4257-b060-324cc63e1429&_gl=1*1a9bi4a*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQzOTI5OS4wLjAuMA..',
		month: 'Март',
		day: 15,
		title: 'Как правильно инвестировать в акции?',
		desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
		name: 'Джон Смит',
		time: '6 мин чтения',
		pfp: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/avatar-4.png?alt=media&token=04cbd91e-6b84-4b79-a551-ce11def28e00&_gl=1*mt1cwe*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQ0MDUyNy4wLjAuMA..',
		tags: ['Обучение', 'Инвестиции', 'Бизнес'],
	},
	{
		category: 'Бизнес',
		img: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/IMG-1.png?alt=media&token=fac7c118-43ba-4f3b-88c5-f51f2f35c15f&_gl=1*89nhkn*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQzOTEyNi4wLjAuMA..',
		month: 'Апрель',
		day: 3,
		title: 'Влияние искусственного интеллекта на будущее технологий',
		desc: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium.',
		name: 'Мария Иванова',
		time: '10 мин чтения',
		pfp: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/avatar-5.png?alt=media&token=9e95323c-f62d-4084-9fe9-cc6332dd9be4&_gl=1*2gyd5s*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQ0MDU1MC4wLjAuMA..',
		tags: ['Технологии', 'Искусственный интеллект', 'Будущее'],
	},
	{
		category: 'Бизнес',
		img: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/IMG-5.png?alt=media&token=51e21c81-5a81-4097-bba6-83da00d5c986&_gl=1*1umyzx7*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQzOTQyMS4wLjAuMA..',
		month: 'Апрель',
		day: 23,
		title: 'Как достичь высоких спортивных результатов?',
		desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
		name: 'Александр Петров',
		time: '8 мин чтения',
		pfp: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/avatar-6.png?alt=media&token=bce8202d-110a-49cc-bb24-42a097b76be2&_gl=1*87tum6*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQ0MDU3NS4wLjAuMA..',
		tags: ['Бизнес', 'Физическая активность'],
	},
	{
		category: 'Менеджмент',
		img: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/IMG-2.png?alt=media&token=ddfd6e42-d2d7-42c1-bf05-c53758f92deb&_gl=1*17ymoma*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQzOTE1NC4wLjAuMA..',
		month: 'Май',
		day: 7,
		title: 'Какие открытия сделала наука за последние годы?',
		desc: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium.',
		name: 'Елена Смирнова',
		time: '5 мин чтения',
		pfp: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/avatar-7.png?alt=media&token=80f94d81-7921-4113-9181-85aa1e1228c7&_gl=1*nsfdfm*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQ0MDU4OC4wLjAuMA..',
		tags: ['Наука', 'Открытия', 'Исследования'],
	},
	{
		category: 'Обучение',
		img: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/IMG-6.png?alt=media&token=5811680e-352c-437e-ab8e-39d4c4c6a78b&_gl=1*ffwhl4*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQzOTYxMy4wLjAuMA..',
		month: 'Май',
		day: 14,
		title: 'Тренды весны 2023: новые коллекции и стили',
		desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
		name: 'Анна Иванова',
		time: '7 мин чтения',
		pfp: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/avatar-8.png?alt=media&token=168cf134-a4c9-48f0-b135-17f589cbc5d0&_gl=1*1rg2spx*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQ0MDYwNC4wLjAuMA..',
		tags: ['Обучение', 'Стиль', 'Тренды'],
	},
	{
		category: 'Сообщество',
		img: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/arabman.png?alt=media&token=6e04354e-64c2-4bce-b807-7b79aca4cae3&_gl=1*m3dxqc*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQzOTA1Ni4wLjAuMA..',
		month: 'Май',
		day: 20,
		title: 'Рецепты мировой кухни: откройте новые вкусы',
		desc: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium.',
		name: 'Мария Козлова',
		time: '6 мин чтения',
		pfp: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/avatar-1.png?alt=media&token=b8654c4e-385a-4c9c-bb30-1475fd20f65f&_gl=1*4y1zis*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQ0MDQ2NS4wLjAuMA..',
		tags: ['Обучение', 'Рецепты', 'Вкусно'],
	},
	{
		category: 'Маркетинг',
		img: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/IMG-3.png?alt=media&token=6aaae566-d924-4f46-9868-6db9cd0df29f&_gl=1*qi34nh*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQzOTM3MS4wLjAuMA..',
		month: 'Май',
		day: 25,
		title: 'Инвестиции и финансовое планирование: советы экспертов',
		desc: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit.',
		name: 'Алексей Петров',
		time: '9 мин чтения',
		pfp: 'https://firebasestorage.googleapis.com/v0/b/e-learning-4f651.appspot.com/o/avatar-2.png?alt=media&token=ad9f9fb3-2b94-4f1a-ae4d-49a2c48c1bd6&_gl=1*1x41ved*_ga*NjcxNzQxMzQzLjE2ODUwOTgzMjk.*_ga_CW55HF8NVT*MTY4NTQzODkxOC41LjEuMTY4NTQ0MDQ3OC4wLjAuMA..',
		tags: ['Маркетинг', 'Инвестиции', 'Планирование'],
	},
] as Array<PostType>;

export const Categories = ['Marketing', 'Community', 'Tutorials', 'Business', 'Management'] as Array<string>;
export const Categories_ru = ['Маркетинг', 'Сообщество', 'Обучение', 'Бизнес', 'Менеджмент'] as Array<string>;
