declare module '*module.css';
declare module '*module.scss';
declare module '*.jpg';
declare module '*.png';
declare module '*.svg';
declare module '*.mp3';
declare module '*.mp4';
declare module 'react-slick';
declare module 'lodash.debounce';
declare module 'react-html5video';
declare module 'react-content-loader'